const STORAGE_KEY='gravity-media-demo';
const initialPosts=[
 {id:'p1',user:'Luna Vale',handle:'lunavale',avatar:'LV',avatarClass:'avatar-purple',time:'2h',text:'The future is not somewhere we go. It is something we create together. ✦\n\nBuilding at the edge of possibility. #FutureIsNow #Design',image:true,likes:248,comments:18,shares:7,liked:false,saved:false,following:false},
 {id:'p2',user:'Arjun Rao',handle:'arjun.builds',avatar:'AR',avatarClass:'avatar-green',time:'5h',text:'A quiet reminder: your best ideas often arrive when the noise goes away.',likes:96,comments:11,shares:3,liked:false,saved:false,following:true},
 {id:'p3',user:'Mira Chen',handle:'mirachen',avatar:'MC',avatarClass:'avatar-blue',time:'1d',text:'What are you exploring this week? Drop it below — I want to discover something new.',likes:61,comments:22,shares:4,liked:false,saved:false,following:false}
];
let state=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||{posts:initialPosts,view:'home',tab:'For You',notifications:0,light:false};
const root=document.getElementById('viewRoot');
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function avatar(p){return `<span class="avatar ${p.avatarClass||'avatar-blue'}">${p.avatar||'GM'}</span>`}
function header(title,eyebrow='Your orbit',action=''){return `<header class="view-header"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1></div><div class="header-actions">${action}<button class="icon-button" aria-label="Create post" id="headerCreate">＋</button></div></header>`}
function postCard(p){return `<article class="post" data-id="${p.id}"><div class="post-head">${avatar(p)}<div class="post-meta"><strong>${p.user} ${p.user==='Luna Vale'?'<span class="verified">✦</span>':''}</strong><small>@${p.handle} · ${p.time}</small></div><button class="icon-button more-post" aria-label="More options">•••</button></div><div class="post-body"><p>${escapeHTML(p.text).replace(/(#[A-Za-z0-9_]+)/g,'<span class="hashtag">$1</span>')}</p>${p.image?'<div class="post-image" role="img" aria-label="Abstract blue and violet cosmic artwork"></div>':''}</div><div class="post-actions"><button class="like-btn ${p.liked?'liked':''}">♡ <span>${p.likes}</span></button><button class="comment-btn">◌ <span>${p.comments}</span></button><button class="share-btn">↗ <span>${p.shares}</span></button><button class="save-btn ${p.saved?'saved':''}">${p.saved?'▣':'□'}</button></div>${p.comments?`<div class="comment-preview"><strong>${p.handle}</strong> ${p.id==='p1'?'This is the energy. ✦':'Absolutely — keeping this in orbit.'} <span>View all ${p.comments} comments</span></div>`:''}</article>`}
function home(){return `${header('Home','Welcome back')}<div class="feed-tabs">${['For You','Following','Latest'].map(x=>`<button class="${state.tab===x?'active':''}" data-tab="${x}">${x}</button>`).join('')}</div><section class="composer"><span class="avatar avatar-blue">NM</span><div style="flex:1"><button class="composer-box" id="openComposer">Share something with the universe...</button><div class="quick-actions"><button id="quickImage">▧ Photo</button><button id="quickPoll">◉ Poll</button><button>◌ Feeling</button></div></div></section><section id="feed">${filteredPosts().map(postCard).join('')}</section>`}
function filteredPosts(){if(state.tab==='Following')return state.posts.filter(p=>p.following||p.handle==='nihaal');if(state.tab==='Latest')return [...state.posts].reverse();return state.posts}
function generic(view,title,desc,icon){return `${header(title,view==='explore'?'Discover beyond your orbit':'Gravity Media')}<div class="empty-state"><div class="empty-icon">${icon}</div><h2>${desc}</h2><p>This surface is planned for Phase 2. Core navigation is active; no simulated content is shown here.</p></div>`}
function profile(){return `${header('Profile','Your identity')}<div class="profile-view"><div class="profile-banner"></div><div class="profile-info"><span class="avatar avatar-blue avatar-large">NM</span><div class="profile-title"><div><h2>nihaal <span class="verified">✦</span></h2><p class="muted">@nihaalmenon96</p></div><button class="outline-button" style="width:auto;padding:9px 16px" id="editProfile">Edit profile</button></div><p class="profile-bio">Building at the intersection of technology, design, and human possibility.</p><span class="profile-links">◉ nihaalmenon.dev</span><div class="profile-stats"><span><strong>128</strong> posts</span><span><strong>2.4k</strong> followers</span><span><strong>486</strong> following</span></div><div class="profile-tabs"><button class="active">Posts</button><button>Reels</button><button>Tagged</button></div></div>${state.posts.filter(p=>p.handle==='nihaal').length?state.posts.filter(p=>p.handle==='nihaal').map(postCard).join(''):'<div class="empty-state"><h2>Your orbit starts here</h2><p>Create your first post to share it with the universe.</p></div>'}</div>`}
function render(){let v=state.view;root.innerHTML=v==='home'?home():v==='profile'?profile():generic(v,v[0].toUpperCase()+v.slice(1),v==='explore'?'Find your next constellation':v==='reels'?'Short-form stories are coming soon':v==='messages'?'Your conversations will appear here':v==='notifications'?'You are all caught up':v==='communities'?'Find your people':v==='marketplace'?'Buy and sell with trust':'Tune your experience',v==='explore'?'⌕':v==='reels'?'▶':v==='messages'?'◌':'✦');bind();document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));}
function bind(){document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>{state.view=el.dataset.view;save();render();});document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>{state.tab=el.dataset.tab;save();render()});document.getElementById('openComposer')?.addEventListener('click',openComposer);document.getElementById('headerCreate')?.addEventListener('click',openComposer);document.getElementById('mobileCreate')?.addEventListener('click',openComposer);document.getElementById('editProfile')?.addEventListener('click',()=>toast('Profile editor will connect to your account backend in Phase 1.'));document.querySelectorAll('.like-btn').forEach(b=>b.onclick=()=>togglePost(b,'liked','likes'));document.querySelectorAll('.save-btn').forEach(b=>b.onclick=()=>togglePost(b,'saved',null));document.querySelectorAll('.comment-btn').forEach(b=>b.onclick=()=>toast('Comments UI is queued for the backend-connected Phase 1 implementation.'));document.querySelectorAll('.share-btn').forEach(b=>b.onclick=()=>toast('Share link generation requires the configured backend.'));}
function togglePost(btn,key,count){let p=state.posts.find(x=>x.id===btn.closest('.post').dataset.id);p[key]=!p[key];if(count)p[count]+=p[key]?1:-1;save();render();}
function openComposer(){document.getElementById('modalRoot').innerHTML=`<div class="modal-backdrop"><form class="modal" id="composerForm"><div class="modal-header"><h2>Create a post</h2><button type="button" class="icon-button" id="closeModal">×</button></div><textarea id="postText" rows="6" maxlength="500" placeholder="Share something with the universe..." required></textarea><div class="modal-footer"><button type="button" class="cancel-button" id="cancelModal">Cancel</button><button class="primary-button">Publish post</button></div></form></div>`;document.getElementById('closeModal').onclick=closeModal;document.getElementById('cancelModal').onclick=closeModal;document.getElementById('composerForm').onsubmit=e=>{e.preventDefault();let text=document.getElementById('postText').value.trim();if(!text)return;state.posts.unshift({id:'local-'+Date.now(),user:'nihaal',handle:'nihaal',avatar:'NM',avatarClass:'avatar-blue',time:'now',text,likes:0,comments:0,shares:0,liked:false,saved:false,following:true});save();closeModal();state.view='home';render();toast('Post saved locally. Connect a backend to publish it securely.')}}
function closeModal(){document.getElementById('modalRoot').innerHTML=''}
function toast(message){let el=document.createElement('div');el.className='toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),3200)}
function escapeHTML(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.getElementById('gravityAI').onclick=()=>window.open('https://gravity-ai-ask-anything.lovable.app/','_blank','noopener');document.getElementById('themeToggle').onclick=()=>{state.light=!state.light;document.body.classList.toggle('light',state.light);save()};document.getElementById('mobileTheme').onclick=()=>{state.light=!state.light;document.body.classList.toggle('light',state.light);save()};document.getElementById('searchInput').onkeydown=e=>{if(e.key==='Enter'&&e.target.value.trim())toast('Search requires backend indexing and privacy-aware access control.')};document.body.classList.toggle('light',state.light);render();
